name: Backend CI Pipeline

on:
  pull_request:
    branches:
      - main
      - backend
  push:
    branches:
      - backend

jobs:
  check-changes-backend:
    runs-on: ubuntu-latest
    outputs:
      backend_dir: ${{ steps.filter.outputs.backend_dir }}
      has_changes: ${{ steps.check_changes.outputs.has_changes }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          backend_dir:
            - 'lnm-backend/**'
    - name: Were backend files changed?
      id: check_changes
      run: |
        echo ${{ steps.filter.outputs.backend_dir }}

        if ${{ steps.filter.outputs.backend_dir }} == 'true'; then
          echo 'There were changes in lnm-backend/**, proceeding...'
          echo "has_changes=true" >> $GITHUB_OUTPUT
        else
          echo 'There were no changes in lnm-backend/**, skipping other jobs...'
          echo "has_changes=false" >> $GITHUB_OUTPUT
        fi
  backend-test:
    runs-on: ubuntu-latest
    needs: check-changes-backend
    if: needs.check-changes-backend.outputs.has_changes == 'true'
    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3
  
      # Шаг 2: Установка JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
  
      # Шаг 3: Кэширование Gradle зависимостей для ускорения сборки
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
  
      # Шаг 4: Сделать gradlew исполняемым
      - name: Grant execute permission for gradlew
        run: chmod +x ./lnm-backend/gradlew
  
      # Шаг 5: Сборка проекта и запуск тестов
      - name: Run tests
        working-directory: ./lnm-backend
        run: ./gradlew test
        env:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      # Шаг 6: Запуск тестов и проверка покрытия
      - name: Run tests and check coverage
        working-directory: ./lnm-backend
        run: ./gradlew check jacocoTestReport
        env:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
  
      # Шаг 7: Публикация отчетов о тестах
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./lnm-backend/build/test-results/test
